#!/bin/bash -l
#SBATCH --ntasks=4
#SBATCH -J FLARES-SWIFT_31
#SBATCH --output=logs/log_%A_%a.txt
#SBATCH -p cosma7-rp
#SBATCH -A dp004
#SBATCH --exclusive
#SBATCH --cpus-per-task=14
#SBATCH --time=08:00:00
#SBATCH --array=0-239  # 240 total tasks for 40 regions and 6 snapshots

module purge
module load gnu_comp/11.1.0 openmpi
module load rockport-settings

# Calculate region and snap based on task ID
region=$((SLURM_ARRAY_TASK_ID / 6))
snap=$((SLURM_ARRAY_TASK_ID % 6))

mpirun $RP_OPENMPI_ARGS -np $SLURM_NTASKS python synthesize_flares_with_agn.py /cosma7/data/dp004/dc-payy1/my_files//flares_pipeline/data/flares.hdf5 --grid bpass-2.2.1-bin_chabrier03-0.1,300.0_cloudy-c17.03.hdf5 --grid-dir /cosma7/data/dp004/dc-seey1/modules/synthesizer-sam/grids --region $region --snap $snap --nthreads $SLURM_CPUS_PER_TASK

echo "Job done, info follows..."
sacct -j $SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
exit
